server:
  port: 8088
spring:
  application:
    name: gateway
  cloud:
    #gateway的优置
    gateway:
      #路由配置
      routes:
        - id: order_route #路由的唯一标识，路由到order
          uri: lb://order-service #需要转发的地址
          #断言规则 用于路由规则
          predicates:
            - Path=/order/**
          #filters:
           # - StripPrefix=1 #转发之前去掉第一层路径 http://ocalhost:8010/order/
    #集成nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nanos
        ephemeral: false
        namespace: 9c1f94ca-8cd4-49d8-b929-e3970c15bad3
